name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore tests
        run: git restore -s origin/feedback src/test/java/org/springframework/samples/petclinic/product/Test1.java src/test/java/org/springframework/samples/petclinic/product/Test10.java src/test/java/org/springframework/samples/petclinic/product/Test2.java src/test/java/org/springframework/samples/petclinic/product/Test3.java src/test/java/org/springframework/samples/petclinic/product/Test4.java src/test/java/org/springframework/samples/petclinic/product/Test5.java src/test/java/org/springframework/samples/petclinic/product/Test6.java src/test/java/org/springframework/samples/petclinic/product/Test7.java src/test/java/org/springframework/samples/petclinic/product/Test8.java src/test/java/org/springframework/samples/petclinic/product/Test9.java       
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
